### ISSUE TITLE
Update index.html for the UI.Router

### ISSUE THREAD

**Issue by ElBedeawi** [JuanjoSalvador/angular-electron#10]
please update the ui router path in index.html
from bower_components to node_modules

**Comment by JuanjoSalvador** [comment]
`ui-router` comes from Bower, that's because I use `bower_components`.

Do you need to install `ui-router` from NPM for any special reason?

Anyway, feel free to fork and change everything you want :)

**Comment by ElBedeawi** [comment]
no i dont you do :D check your package.json line 24 
may be i'm missing something but i couldn't make it work till i updated index.html to look for it in node_modules rather than bower_components

**Comment by JuanjoSalvador** [comment]
Okey, I've tested it and you're right. I just removed bower dependencies, now all comes from node.

Thanks for reporting!
