### ISSUE TITLE
Interesante

### ISSUE THREAD

**Issue by blinkuz** [JuanjoSalvador/angular-electron#7]
Es un excelente proyecto, estoy super interesado en el, ya que soy desarrollador angularjs y me estoy adentrando al mundo de electron y seria super genial poder utilizar angular en electronjs, pero tengo algunas preguntas, lo que tienes esta funcionando ?  has logrado algun resultado con lo que tienes ya creado ?

**Comment by JuanjoSalvador** [comment]
Aún no está terminado, todavía me quedan algunas cosas que perfilar, pero por ejemplo, con lo que hay subido, puedes lanzar una aplicación en Electron que corra con AngularJS sin problema alguno.

Haz la prueba ;) Solo hay que clonar, instalar dependencias (con `npm install` y `bower install`), y a volar.

**Comment by blinkuz** [comment]
Me gustaria aprender un poco mas de electron con angularjs, mmm no tendras algun material de aprendizaje para profundisar un poco mas el tema, voy a clonar tu repositorio y espero que avances mucho en tu proyecto.

**Comment by JuanjoSalvador** [comment]
Hombre, este proyecto concreto no puede avanzar mucho más, a decir verdad, es una semilla. Hay otro que tengo en privado, que usa esta misma semilla, y que liberaré pronto, que podría servirte de apoyo.

Lamentablemente no tengo recursos que puedan ayudarte :( Con Electron yo también soy *bastante* novato, realmente.

**Comment by blinkuz** [comment]
Ya estoy viendo todo lo que tienes hay e incluso agregando algunos plugins mas de gulp como HAML para mejorar el rendimiento al escribir el HTML, y tengo una pregunta el plugin pump que es lo que hace he buscado en gulpjs.com pero no encuentro nada de referencia.

**Comment by JuanjoSalvador** [comment]
Nada útil, realmente. Acabo de corregirlo y eliminarlo. Intenté comprimir todo el código JS de la aplicación usando Gulp, pero no salió como esperaba, y realmente es innecesario. En un futuro podría usarse Webpack para esto.

Lo de HAML me parece interesante, pero es un sistema de plantillas, ¿no? Si se puede compatibilizar con el sistema de directivas de Angular, no veo por qué no añadirlo.

Con respeto a los tutoriales que me pediste, he encontrado esto, que además añade algunos bindings para VS Code, puede serte de utilidad ;-)

> https://scotch.io/tutorials/creating-desktop-applications-with-angularjs-and-github-electron

**Comment by blinkuz** [comment]
Excelente, gracias por el tutorial lo mirare, otra cosa es que ya estoy haciendo pruebas con haml y las directivas de angular, tambien estoy probando con directivas personalizadas, otra cosa es que le agregare el plugin plumber para el manejo de errores ya que cuando se trabaja con sass o haml suelen ocurrir errores al compilar y no seria recomendado detener la ejecucion de las demas tareas.

**Comment by JuanjoSalvador** [comment]
Tenía pensado añadir [Protractor](http://www.protractortest.org/#/) para los tests de Angular y [Travis-CI](https://travis-ci.org/) para la integración continua, así que ahora que lo mencionas, podría añadirse manejo de errores en Gulp para SASS.

**Comment by blinkuz** [comment]
Con el [plumber](https://www.npmjs.com/package/gulp-plumber/) se puede capturar los errores de cual tarea que se este ejecutando en gulp, no importa que sea compilar SASS,CofeeScript o Haml el muestra el error y continua con la ejecucion de las tareas si quieres miralo.

**Comment by JuanjoSalvador** [comment]
He abierto una tarea nueva, siéntete libre de contribuir :yum:

**Comment by blinkuz** [comment]
Excelente, no soy muy bueno en esto de trabajar con Github pero intentare contribuir con lo que pueda.

**Comment by JuanjoSalvador** [comment]
Cualquier excusa es buena para aprender a manejarse con Git y Github!
